category/urls.py
from django.urls import path
from . import views
app_name = 'category'
urlpatterns = [
    path(r'PC_all', views.pc_full, name = "pc_full"),
    path(r'Console_all', views.con_full, name = 'con_full'),

]

post/urls.py
from django.urls import path
from . import views
app_name = 'post'
urlpatterns = [
    path(r'', views.index , name = 'home'),
    path(r'about', views.about, name= 'about'),
    path(r'<post_urls>', views.detail, name='detail'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('post.urls')),
    path(r'category/', include('category.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=30)
	date_time = models.DateField(auto_now_add=True)
	main_img = models.FileField()
	main_text = models.TextField()
	cate = models.CharField(max_length=30)
	url_pat = models.CharField(max_length=30, default = 'null' )
	
class Detail(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	img1 = models.FileField()

category/views.py
from django.shortcuts import render, get_object_or_404
from post.models import Post, Detail

def pc_full(request):
	post_pc =  Post.objects.filter(cate = 'P.C').order_by('-date_time')
	return render (request, 'pc_full.html', {'post_pc': post_pc})

def con_full(request):
	post_con =  Post.objects.filter(cate = 'Console').order_by('-date_time')
	return render (request, 'con_full.html', {'post_con': post_con})

post/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Detail

def  index (request):
	post_pc =  Post.objects.order_by('-date_time')
	
	return render (request, 'home.html', {'post_pc':post_pc})

def about (request):
	return render (request, 'about.html')

def detail(request, post_urls):
	posts = Post.objects.all()
	post_id = 0
	for pot in posts:
		if post_urls == pot.url_pat:
			post_id = pot.pk

	post = get_object_or_404(Post, pk = post_id)
	return render (request, 'detail.html', {'post': post})

templates/about.html
{% extends 'base.html' %}
{% block about_active %}active{% endblock %}
{% block title %}Game-point-About{% endblock %}
{% block body %}
<div class="container-fluid">
	<h1 class="bd-tytle">About</h1>
	<p>We at Game-point try to provide the information about the latest games.</p>
</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Game-point{% endblock %}</title>
        {% load static %}
        <link rel="shortcut icon" type="image/png" href="{%  static "favicon.jpg" %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet"  href="{% static "style.css" %}">
        <script type="text/javascript" src="{% static "main.js" %}"></script>
        
    </head>
    <body background="">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class= "navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'post:home' %}">Game-point</a>
                </div>
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
                        <li class="{% block home_active %}{% endblock %}"><a href="{% url 'post:home' %}">&nbsp; Home</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'category:pc_full' %}">P.C</a></li>
                                <li><a href="{% url 'category:con_full' %}">Console</a></li>
                            </ul>
                        <li class="{% block about_active %}{% endblock %}"><a href="{% url 'post:about' %}">&nbsp; About</a></li>
                    </ul>
                    <form class="navbar-form navbar-right" role="search" method="get" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

templates/con_full.html
{% extends 'base.html' %}
{% block title %}Game-point_All_Console_games{% endblock %}
{% block body %}
<h1 class="bd-tytle">Console Games</h1>
<div class="row">
{% for posts  in post_con %}
    <div class="col-sm-4 col-lg-2">
      <div class="thumbnail">
              <a href="{% url 'post:detail' post.url_pat %}">
                  <img src="{{ posts.main_img.url }}" class="img-responsive">
              </a>
             <div class="caption">
                  <h2>{{posts.title}}</h2>
                  <h4>{{posts.cate}}</h4>
                  <!-- View Details -->
                  <a href="{% url 'post:detail' post.url_pat %}" class="btn btn-primary btn-sm" role="button">View Details</a>
              </div>
    </div>
    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
  </div>
{% endfor %}
</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block title %}{{post.title}}{% endblock %}
{% block body %}
<div class="container-fluid">
	<!-- Left Album Info -->
	<div class = "row">
		<div class="col-sm-4 col-md-3">
	            <div class="panel panel-default">
	                <div class="panel-body">
	                    <a href="{% url 'post:detail' post.title %}">
	                        {% if post.main_img %}
	                            <img src="{{ post.main_img.url }}" class="img-responsive">
	                        {% else %}
	                            <h3>No image to display</h3>
	                        {% endif %}
	                    </a>
	                    <h1>{{ post.title }} <small></small></h1>
	                    <h2>{{ post.cate }}</h2>
	                </div>
	            </div>
	        </div>
	        <!-- Right Song Info -->
	        <div class="col-sm-8 col-md-9">
	            <div class="panel panel-default">
	                <div class="panel-body">
	                	<img class="img-responsive" src="{{post.main_img.url}}" >
						<p class="font-weight-light">{{post.main_text}}</p>
					</div>
				</div>
			</div>
	</div>
	<div class="row">
		<div class="col-12" id=#images>
			<div class="panel panel-default">
				<div class="panel-body" id = #img-pan>
					<div class="row">
						
						{% for img in post.detail_set.all %}
							<div class="col-3">
							<img class="img-responsive" id = #images  src="{{ img.img1.url }}" >
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{%endblock%}

templates/home.html
{% extends 'base.html' %}
{% block home_active %}active{% endblock %}
{% block body %}
<h1 class="bd-tytle">Resent Posts</h1>
<div class="row">
{% for posts  in post_pc %}
		<div class="col-sm-4 col-lg-2">
			<div class="thumbnail">
	            <a href="{% url  'post:detail' posts.url_pat %}">
	                <img src="{{ posts.main_img.url }}" class="img-responsive">
	            </a>
	           <div class="caption">
	                <h2>{{posts.title}}</h2>
	                <h4>{{posts.cate}}</h4>
	              	<!-- View Details -->
	                <a href="{% url  'post:detail' posts.url_pat  %}" class="btn btn-primary btn-sm" role="button">View Details</a>
	            </div>
		</div>
		{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
	</div>
{% endfor %}
</div>
{%endblock%}

templates/pc_full.html
{% extends 'base.html' %}
{% block title %}Game-point_All_PC_games{% endblock %}
{% block body %}
<h1 class="bd-tytle">P.C Games</h1>
<div class="row">
{% for posts  in post_pc %}
		<div class="col-sm-4 col-lg-2">
			<div class="thumbnail">
	            <a href="#">
	                <img src="{{ posts.main_img.url }}" class="img-responsive">
	            </a>
	           <div class="caption">
	                <h2>{{posts.title}}</h2>
	                <h4>{{posts.cate}}</h4>
	              	<!-- View Details -->
	                <a href="" class="btn btn-primary btn-sm" role="button">View Details</a>
	            </div>
		</div>
		{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
	</div>
{% endfor %}
</div>
{% endblock %}